<?php 

/**
 * 
 * =======================================================================
 * 
 * Script to export reading list author affiliation data to a CSV file 
 * for Library staff to do further processing   
 * 
 * =======================================================================
 * 
 * Input: 
 * JSON-encoded list of citations on STDIN 
 * 
 * Output: 
 * CSV-format table of citations with affiliation data 
 * 
 * =======================================================================
 *
 * Typical usage: 
 * php simpleCsvExport.php <Data/4.json >Data/5.csv 
 * 
 * The input citation data is assumed to already contain data from Leganto, Alma, Scopus and VIAF  
 * 
 * See getCitationsByCourseAndList.php, enhanceCitationsFromAlma.php 
 * enhanceCitationsFrom Scopus.php and enhanceCitationsFromViaf.php for how this data is prepared  
 * 
 * The script also assumes a World Bank ranking file is present which has been generated by 
 * makeWorldBankRankings.php  
 * 
 * 
 * =======================================================================
 * 
 * General process: 
 * 
 * Make an empty result set to popuplate 
 * 
 * Loop over citations - for each citation:  
 *  - Assemble the relevant data from the different sources
 *  - Calculate a numeric CSI for the citation
 *  - Add the resulting record to the result set   
 *    
 * Export the result set as JSON 
 * 
 * =======================================================================
 * 
 * 
 * 
 * !! Gotchas !!  
 * 
 * The output CSV file is (like all the other data in this project) UTF-8-encoded
 * But Excel expects ANSI-encoded CSV files and will not open files as UTF-8 
 * So special characters hash in Excel 
 * This does not matter in development but 
 * TODO: We need a robust way to export UTF-8 data ina form that Excel will open 
 * e.g. use a software library to export an .xlsx file directly  
 * 
 * Different sources variously use ISO-2-letter country codes, ISO-3-letter country codes and country names 
 * During the earlier stages of the process (enhanceCitations...) we simply take the data exactly as provided 
 * During this CSV-export process we have to convert everything to a single standard format 
 * Currently we are using ISO-2-letter codes but this could change 
 * For conversion we use JSON mapping tables downloaded from http://country.io/data/ and saved in Config/CountryCodes 
 * Some sources have some records with error or placeholder codes (e.g. "XX") and some have free-text country names in 
 * other languages - currently we ignore anything we cannot recognise  
 * TODO: For a production service we may want to build config data with e.g. translations of country names from other languages
 * 
 * Some affiliation data does not contain country codes or names e.g. the 5xx fields in VIAF might contain a city or an institution 
 * We currently are not using it but 
 * TODO: in a production system we might want to look at whether we can lookup institutions and find their countries 
 *    
 *    
 * 
 * 
 * 
 */


error_reporting(E_ALL);                     // we want to know about all problems


require_once("utils.php"); 


$outFormat = "TXT"; 

// country codes 
$iso3Map = json_decode(file_get_contents("Config/CountryCodes/iso3.json"), TRUE);
$namesMap = json_decode(file_get_contents("Config/CountryCodes/names.json"), TRUE);
$continentMap = json_decode(file_get_contents("Config/CountryCodes/continent.json"), TRUE);
$iso2Map = array_flip($iso3Map); 
$namesToCodesMap = array_change_key_case(array_flip($namesMap));




// World Bank rankings 
$worldBankRank = Array(); 
$worldBankMaxRank = NULL; 
$worldBankRankLines = file($config["World Bank"]["RankFile"], FILE_IGNORE_NEW_LINES | FILE_SKIP_EMPTY_LINES);
$columnNames = explode("\t", array_shift($worldBankRankLines));   
foreach ($worldBankRankLines as $worldBankRankLine) { 
    $entry = explode("\t", $worldBankRankLine);
    $entry = array_combine($columnNames, $entry); // turn numeric to text column ids
    if (isset($entry["Country Code [2]"]) && $entry["Country Code [2]"]) {
        $worldBankRank[$entry["Country Code [2]"]] = $entry["Rank"]; 
        if (!$worldBankMaxRank || $entry["Rank"]>$worldBankMaxRank) {
            $worldBankMaxRank = $entry["Rank"]; 
        }
    }
}
// World Bank country code aliases 
$worldBankAlias = json_decode(file_get_contents("Config/WorldBank/alias.json"), TRUE); 
foreach ($worldBankAlias as $source=>$target) {
    if (!isset($worldBankRank[$source])) { // only alias if we really don't have it  
        $worldBankRank[$source] = $worldBankRank[$target];
    }
} 



$citations = json_decode(file_get_contents("php://stdin"), TRUE);

$outputRecords = Array(); 
// $rowHeadings = Array("TYPE", "TITLE", "AUTHOR", "TAGS", "NATIONALITIES", "CONTINENTS", "SOURCES", "CSI", "CSI-AUTHORS", "CSI-SUM");   
$rowHeadings = Array("CIT-TYPE", "CIT-TITLE", "CIT-CONTAINER", "CIT-AUTHOR", "SIMILARITY", "SOURCE", "SOURCE-AUTHORS", "SOURCE-COUNTRIES");
// $rowHeadings = Array("TYPE", "TITLE", "CONTAINER-TITLE", "AUTHOR", "TAGS", "NATIONALITIES", "CSI");

foreach ($citations as $citation) { 
    
    $outputRecord = Array();
    $outputRecord["NOTES"] = Array();
    
    if (!isset($citation["Leganto"])) {
        trigger_error("Cannot export data if no Leganto data in source", E_USER_ERROR);
    } 
            
    if (isset($citation["Leganto"]["secondary_type"])) { 
        $outputRecord["CIT-TYPE"] = $citation["Leganto"]["secondary_type"]["desc"];
    }
    $outputRecord["TAGS"] = Array(); 
    if (isset($citation["Leganto"]["section_tags"])) {
        foreach ($citation["Leganto"]["section_tags"] as $tag) {
            $outputRecord["TAGS"][] = $tag["desc"];
        }
    }
    if (isset($citation["Leganto"]["citation_tags"])) {
        foreach ($citation["Leganto"]["citation_tags"] as $tag) { 
            $outputRecord["TAGS"][] = $tag["desc"];
        }
    }
    if (isset($citation["Leganto"]["metadata"]["title"])) {
        $outputRecord["CIT-TITLE"] = $citation["Leganto"]["metadata"]["title"];
    } else if (isset($citation["Leganto"]["metadata"]["journal_title"])) {
        $outputRecord["CIT-TITLE"] = $citation["Leganto"]["metadata"]["journal_title"];
    }
    
    if (isset($citation["Leganto"]["metadata"]["article_title"])) {
        if (isset($outputRecord["CIT-TITLE"])) { $outputRecord["CIT-CONTAINER"] = $outputRecord["CIT-TITLE"]; } 
        $outputRecord["CIT-TITLE"] = $citation["Leganto"]["metadata"]["article_title"];
    } else if (isset($citation["Leganto"]["metadata"]["chapter_title"])) {
        if (isset($outputRecord["CIT-TITLE"])) { $outputRecord["CIT-CONTAINER"] = $outputRecord["CIT-TITLE"]; }
        $outputRecord["CIT-TITLE"] = $citation["Leganto"]["metadata"]["chapter_title"];
    }
    
    if (isset($citation["Leganto"]["metadata"]["author"])) {
        $outputRecord["CIT-AUTHOR"] = $citation["Leganto"]["metadata"]["author"];
    }
    
    $outputRecord["NATIONALITIES"] = Array();
    $outputRecord["CONTINENTS"] = Array();
    $outputRecord["SOURCES"] = Array();
    $outputRecord["CSI"] = "";  // default 
    $outputRecord["GNI-RANKS"] = Array();
    
    
    $gniRanks = Array();    // one value for each author - higher values for higher GNI countries 
                            // where an author has more than one affiliation entry is the mean of all the individual ranks 
                            // authors from VIAF and from Scopus count as separate authors (even though they are probably the same) 
                            // so an item with only one author and data from VIAF and from Scopus will have *two* entries 
                            // Scopus affiliation is taken from contemporary affiliation (abstract) where possible
                            // and if not from the current affiliation (profile) 
    
    
    $sources = Array(); 
    
    
    if (isset($citation["Scopus"])) {
        
        
        if (isset($citation["Scopus"]["first-match"]) && isset($citation["Scopus"]["first-match"]["authors"])) {
            
            $outputRecord["DATA"][] = "SCOPUS";
            $outputRecord["SCOPUS-MATCH"] = "Y";
            $outputRecord["SCOPUS-AUTHORS"] = Array(); 
            $outputRecord["SCOPUS-COUNTRY-CODES"] = Array();
            $outputRecord["SCOPUS-COUNTRIES"] = Array(); 
            
            // $outputRecord["SCOPUS-SA"] = $citation["Scopus"]["first-match"]["similarity-authors"];
            // $outputRecord["SCOPUS-ST"] = $citation["Scopus"]["first-match"]["similarity-title"];
            
            
            $totalSimilarity = 0;
            $countSimilarity = 0;
            
            
            foreach ($citation["Scopus"]["first-match"]["authors"] as $author) {
                
                $gniRanksAuthorSource = Array(); // just for this author, this source
                $contemporaryAffiliation = FALSE; // set to TRUE if we find one
                
                
                $totalSimilarity += floor($author["similarity-title"]*$author["similarity-author"]/100);
                $countSimilarity++; 
                
                $outputRecord["SCOPUS-AUTHORS"][] = $author["ce:indexed-name"]; 
                
                $thisAuthorCountries = Array(); 
                
                if (isset($author["affiliation"]) && is_array($author["affiliation"])) {
                    foreach ($author["affiliation"] as $authorAffiliation) {
                        
                        $sources["Scopus-contemporary"] = TRUE;
                        
                        if (isset($authorAffiliation["country"])) {
                            if (isset($namesToCodesMap[strtolower($authorAffiliation["country"])])) {
                                $nationalityCode = $namesToCodesMap[strtolower($authorAffiliation["country"])];
                                if (isset($worldBankRank[$nationalityCode])) {
                                    $gniRanksAuthorSource[] = $worldBankRank[$nationalityCode];
                                } else {
                                    trigger_error("No World Bank ranking for ".$nationalityCode, E_USER_ERROR);
                                }
                                $thisAuthorCountries[] = $nationalityCode;
                                $contemporaryAffiliation = TRUE;
                            } else {
                                // trigger_error("Can't derive nation code for ".$authorAffiliation["country"], E_USER_NOTICE);
                            }
                        }
                    }
                }
                if (!$contemporaryAffiliation) { // no contemporary affiliation, try current instead
                    if (isset($author["affiliation-current"]) && is_array($author["affiliation-current"])) {
                        
                        $outputRecord["NOTES"][] = "Scopus: using current affiliation for at least one author";
                        
                        foreach ($author["affiliation-current"] as $authorAffiliation) {
                            
                            $sources["Scopus-current"] = TRUE;
                            
                            if (isset($authorAffiliation["address"])) {
                                
                                $nationalityCode = NULL;
                                if (isset($authorAffiliation["address"]["@country"])) {
                                    // 3-digit code
                                    $nationalityValue = strtoupper($authorAffiliation["address"]["@country"]);
                                    if (isset($iso2Map[$nationalityValue]) && $iso2Map[$nationalityValue]) {
                                        if (!in_array($iso2Map[$nationalityValue], Array("XX", "ZZ"))) {
                                            $nationalityCode = $iso2Map[$nationalityValue];
                                        }
                                    }
                                }
                                if ($nationalityCode==NULL && isset($authorAffiliation["address"]["country"])) {
                                    // country name
                                    $nationalityValue = strtolower($authorAffiliation["address"]["country"]);
                                    if (isset($namesToCodesMap[$nationalityValue])) {
                                        $nationalityCode = $namesToCodesMap[$nationalityValue];
                                    }
                                }
                                if ($nationalityCode!==NULL) {
                                    if (isset($worldBankRank[$nationalityCode])) {
                                        $gniRanksAuthorSource[] = $worldBankRank[$nationalityCode];
                                    } else {
                                        trigger_error("No World Bank ranking for ".$nationalityCode, E_USER_ERROR);
                                    }
                                    $thisAuthorCountries[] = $nationalityCode;
                                } else {
                                    // trigger_error("Can't derive nation code for ".$authorAffiliation["address"]["@country"].":".$authorAffiliation["address"]["country"], E_USER_NOTICE);
                                }
                                
                            }
                            
                        }
                    }
                }

                
                
                $outputRecord["SCOPUS-COUNTRY-CODES"][] = implode(",", array_unique($thisAuthorCountries));
                $outputRecord["SCOPUS-COUNTRIES"][] = implode(",", array_map(function($code) use ($namesMap) { return ( isset($namesMap[$code]) && $namesMap[$code] ) ? $namesMap[$code] : $code; }, array_unique($thisAuthorCountries))); 
                
                if (count($gniRanksAuthorSource)) {
                    $gniRanks[] = array_sum($gniRanksAuthorSource)/count($gniRanksAuthorSource);
                }
            }
            
            
            if ($countSimilarity) {
                $outputRecord["SCOPUS-SIMILARITY"] = floor($totalSimilarity/$countSimilarity);
            }
            
        }
    }
    

    
    if (isset($citation["VIAF"])) { 
        
        $outputRecord["DATA"][] = "VIAF"; 
        $outputRecord["VIAF-MATCH"] = "Y"; 
        $outputRecord["VIAF-AUTHORS"] = Array();
        $outputRecord["VIAF-COUNTRY-CODES"] = Array();
        $outputRecord["VIAF-COUNTRIES"] = Array();
        
        
        if (count($citation["VIAF"])) {
            $outputRecord["VIAF-SA"] = 0; // we will sum these across all authors and then divide by number of authors after the loop 
            $outputRecord["VIAF-ST"] = 0;
        }
        
        
        $totalSimilarity = 0; 
        $countSimilarity = 0; 
        foreach ($citation["VIAF"] as $viafCitation) { 
            
            if ($viafCitation["data-source"]=="Scopus") {
                $outputRecord["NOTES"][]="VIAF: cross-search from Scopus results";
            }
            if ($viafCitation["data-source"]=="Leganto") {
                $outputRecord["NOTES"][]="VIAF: search from Leganto citation";
            }
            
            if (isset($viafCitation["best-match"])) {
                
                $totalSimilarity += floor($viafCitation["best-match"]["similarity-title"]*$viafCitation["best-match"]["similarity-author"]/100);
                $countSimilarity++; 
                
                $outputRecord["VIAF-SA"] += $viafCitation["best-match"]["similarity-author"]; 
                $outputRecord["VIAF-ST"] += $viafCitation["best-match"]["similarity-title"];
                
                $outputRecord["VIAF-AUTHORS"][] = $viafCitation["best-match"]["heading"];
                $thisAuthorCountries = Array();
                
                
                
                $gniRanksAuthorSource = Array(); // just for this author, this source 
                
                foreach (Array("NAT"=>"nationalities") as $fieldCode=>$countryField) { 
                    
                    if (isset($viafCitation["best-match"][$countryField]) && is_array($viafCitation["best-match"][$countryField])) { 
                    
                        foreach ($viafCitation["best-match"][$countryField] as $nationality) {
                            
                            $nationalityValue = strtoupper($nationality["value"]);
                            $nationalityCode = NULL;
                            if (strlen($nationalityValue)==2) {
                                if (!in_array($nationalityValue, Array("XX", "ZZ"))) {
                                    $nationalityCode = $nationalityValue;
                                }
                            } else if (strlen($nationalityValue)==3) {
                                if (isset($iso2Map[$nationalityValue]) && $iso2Map[$nationalityValue]) {
                                    if (!in_array($iso2Map[$nationalityValue], Array("XX", "ZZ"))) {
                                        $nationalityCode = $iso2Map[$nationalityValue];
                                    }
                                }
                            }
                            if ($nationalityCode==NULL && isset($namesToCodesMap[strtolower($nationality["value"])])) {
                                // is a country name
                                $nationalityValue = strtolower($nationality["value"]);
                                if (isset($namesToCodesMap[$nationalityValue])) {
                                    $nationalityCode = $namesToCodesMap[$nationalityValue];
                                }
                            }
                            if ($nationalityCode!==NULL) {
                                $sources["VIAF-$fieldCode"] = TRUE;
                                if (isset($worldBankRank[$nationalityCode])) {
                                    $gniRanksAuthorSource[] = $worldBankRank[$nationalityCode];
                                } else {
                                    trigger_error("No World Bank ranking for ".$nationalityCode, E_USER_ERROR);
                                }
                                $thisAuthorCountries[] = $nationalityCode;
                            } else {
                                // trigger_error("Can't derive nation code for ".$nationality["value"], E_USER_NOTICE);
                            }
                            
                        }
                    }
                    
                }
                if (count($gniRanksAuthorSource)) { 
                    $gniRanks[] = array_sum($gniRanksAuthorSource)/count($gniRanksAuthorSource);
                }
                $outputRecord["VIAF-COUNTRY-CODES"][] = implode(",", array_unique($thisAuthorCountries));
                $outputRecord["VIAF-COUNTRIES"][] = implode(",", array_map(function($code) use ($namesMap) { return ( isset($namesMap[$code]) && $namesMap[$code] ) ? $namesMap[$code] : $code; }, array_unique($thisAuthorCountries)));
                
                
            }

            
        }
        
        if ($countSimilarity) { 
            $outputRecord["VIAF-SIMILARITY"] = floor($totalSimilarity/$countSimilarity); 
        }
        
        if (count($citation["VIAF"])) {
            $outputRecord["VIAF-SA"] = $outputRecord["VIAF-SA"]/count($citation["VIAF"]); 
            $outputRecord["VIAF-ST"] = $outputRecord["VIAF-ST"]/count($citation["VIAF"]); 
        }
        
    }
    
    
    
    $outputRecord["SIMILARITY"] = NULL; 
    $outputRecord["SOURCE"] = NULL;
    $outputRecord["SOURCE-AUTHORS"] = NULL;
    $outputRecord["SOURCE-COUNTRY-CODES"] = NULL;
    $outputRecord["SOURCE-COUNTRIES"] = NULL;
    
    // filter and combine VIAF and Scopus data 
    if (in_array($citation["Leganto"]["secondary_type"]["desc"], Array("CR", "E_CR"))) {    // article-ish
        $sourcePreferences = Array("SCOPUS", "VIAF"); 
    } else {
        $sourcePreferences = Array("VIAF", "SCOPUS");
    }
    foreach ($sourcePreferences as $sourcePreference) { 
        if (isset($outputRecord["DATA"]) && 
            is_array($outputRecord["DATA"]) && 
            in_array($sourcePreference, $outputRecord["DATA"]) && 
            $outputRecord["$sourcePreference-MATCH"]=="Y" && 
            isset($outputRecord["$sourcePreference-SIMILARITY"]) && 
            $outputRecord["$sourcePreference-SIMILARITY"]>=80 && 
            count($outputRecord["$sourcePreference-COUNTRIES"]) && 
            implode("", $outputRecord["$sourcePreference-COUNTRIES"])>""
        ) { 
            $outputRecord["SOURCE"] = $sourcePreference;
            $outputRecord["SIMILARITY"] = $outputRecord["$sourcePreference-SIMILARITY"];
            $outputRecord["SOURCE-AUTHORS"] = $outputRecord["$sourcePreference-AUTHORS"];
            $outputRecord["SOURCE-COUNTRY-CODES"] = $outputRecord["$sourcePreference-COUNTRY-CODES"];
            $outputRecord["SOURCE-COUNTRIES"] = $outputRecord["$sourcePreference-COUNTRIES"];
            break; // don't check any more sources 
        }
    }
    
    
    
    
    $outputRecord["SOURCES"] = array_keys($sources);
    
    $outputRecord["NOTES"] = array_unique($outputRecord["NOTES"]);
    
    $outputRecord["NATIONALITIES"] = array_unique($outputRecord["NATIONALITIES"]);
    
    foreach ($outputRecord["NATIONALITIES"] as $nationCode) {
        if (isset($continentMap[$nationCode]) && $continentMap[$nationCode]) {
            $outputRecord["CONTINENTS"][] = $continentMap[$nationCode];
        }
    }
    $outputRecord["CONTINENTS"] = array_unique($outputRecord["CONTINENTS"]);
    
    if (count($gniRanks) && $worldBankMaxRank) {
        $outputRecord["CSI"] = array_sum($gniRanks)/($worldBankMaxRank*count($gniRanks));
        $outputRecord["GNI-RANKS"] = $gniRanks; 
    }
    
    $outputRecords[] = $outputRecord; 
    
}





if ($outFormat == "CSV") {
    $out = fopen('php://output', 'w');
    fputcsv($out, $rowHeadings);
} else if ($outFormat == "TXT") {
    print implode("\t", $rowHeadings)."\n";
}

foreach ($outputRecords as $outputRecord) {
    $outputRow = Array();
    foreach ($rowHeadings as $rowHeading) {
        $outputField = FALSE;
        if (!isset($outputRecord[$rowHeading])) {
            $outputField = "";
        } else if (is_array($outputRecord[$rowHeading])) {
            $outputField = implode("|", $outputRecord[$rowHeading]);
        } else {
            $outputField = $outputRecord[$rowHeading];
        }
        $outputRow[] = $outputField;
    }
    if ($outFormat == "CSV") {
        fputcsv($out, $outputRow);
    } else if ($outFormat == "TXT") {
        print implode("\t", $outputRow)."\n";
    }
}

if ($outFormat == "CSV") {
    fclose($out);
} else if ($outFormat == "TXT") {
}






?>